### PR TITLE
Change cargo category to cryptography

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: stratis-storage/project#413

### CODE REVIEW

**Comment by mulkieran** [comment]
I think you should add "api-bindings" to all the high-level bindings, not the "-sys" ones, as well.

**Review by mulkieran — CHANGES_REQUESTED** [review]
Definitely add os::linux-apis to both. I looked at the category breakdown, and that makes sense to me. See: https://crates.io/categories/os.

**Review by mulkieran — APPROVED** [review]

**Comment by mulkieran** [comment]
I think this is complete. @jbaublitz Does this look good to you?

**Review by jbaublitz — APPROVED** [review]

**Comment by jbaublitz** [comment]
Yep! Looks good to me.

**Comment by bgurney-rh** [comment]
OK, I'm going to create a new PR.

**Pull request closed without merging**
