### PR TITLE
travis.yml: make yamllint compliant

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: stratis-storage/project#169

### CODE REVIEW

**Comment by mulkieran** [comment]
Looks good! Now for the yamllint task!

**Comment by jbaublitz** [comment]
> Looks good! Now for the yamllint task!

@mulkieran Do you mean that this PR will also add a CI task to run yamllint on `.travis.yml`? If so, I'll hold off on reviewing.

**Comment by mulkieran** [comment]
> > Looks good! Now for the yamllint task!
> 
> @mulkieran Do you mean that this PR will also add a CI task to run yamllint on `.travis.yml`? If so, I'll hold off on reviewing.

@jbaublitz Yes, we might as well do that, and make sure the file stays well formatted.

**Comment by bgurney-rh** [comment]
I'm trying to figure out how to have Travis execute yamllint on the .travis.yml file, and the last commit didn't work:

```
yamllint: command not found
```

**Comment by jbaublitz** [comment]
> I'm trying to figure out how to have Travis execute yamllint on the .travis.yml file, and the last commit didn't work:
> 
> ```
> yamllint: command not found
> ```

I don't think `yamllint` is installed by default. I think you need to explicitly install it here:
```
addons:
```

**Comment by bgurney-rh** [comment]
I was thinking of adding this to "jobs:".. "include:"; would it work?
```
    - name: "run yamllint on .travis.yml"
      python: "3.7.6"
      install: pip install yamllint
      script: yamllint .travis.yml
```

**Comment by jbaublitz** [comment]
@bgurney-rh 
```
addons:
  apt:
    packages:
      - [keep existing packages here]
      - yamllint
```
should also work. It depends on what version of yamllint we want. @mulkieran do you have any thoughts?

**Comment by mulkieran** [comment]
> @bgurney-rh
> 
> ```
> addons:
>   apt:
>     packages:
>       - [keep existing packages here]
>       - yamllint
> ```
> 
> should also work. It depends on what version of yamllint we want. @mulkieran do you have any thoughts?

We've been splitting out dependencies into the separate targets that require them, so I'ld keep that approach. We also set the version usually from the Fedora 30 standard, so let's go with:

```
pip install yamllint==1.20.0
```

Also, change title a bit to mention recommended development interpreter.

**Comment by bgurney-rh** [comment]
OK; hopefully I covered all of the recommendations in the last force-push.  Let's see how this works.

**Comment by bgurney-rh** [comment]
That last attempt failed with this error:
```
$ pip install yamllint==1.20.0

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

Collecting yamllint==1.20.0

  Downloading https://files.pythonhosted.org/packages/0f/3e/a3d6c73d8e7aee22faba6d96f9b8e24a5db425f42851922aa99e1bef328a/yamllint-1.20.0-py2.py3-none-any.whl (57kB)

     |████████████████████████████████| 61kB 1.9MB/s 

Collecting pathspec>=0.5.3 (from yamllint==1.20.0)

  Downloading https://files.pythonhosted.org/packages/5d/d0/887c58853bd4b6ffc7aa9cdba4fc57d7b979b45888a6bd47e4568e1cf868/pathspec-0.8.0-py2.py3-none-any.whl

Requirement already satisfied: pyyaml in /usr/lib/python2.7/dist-packages (from yamllint==1.20.0) (3.12)

Installing collected packages: pathspec, yamllint

ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pathspec-0.8.0.dist-info'

Consider using the `--user` option or check the permissions.

WARNING: You are using pip version 19.2.1, however version 20.0.2 is available.

You should consider upgrading via the 'pip install --upgrade pip' command.

The command "pip install yamllint==1.20.0" failed and exited with 1 during .
```

**Comment by mulkieran** [comment]
> That last attempt failed with this error:
> 
> ```
> $ pip install yamllint==1.20.0
> 
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
> 
> Collecting yamllint==1.20.0
> 
>   Downloading https://files.pythonhosted.org/packages/0f/3e/a3d6c73d8e7aee22faba6d96f9b8e24a5db425f42851922aa99e1bef328a/yamllint-1.20.0-py2.py3-none-any.whl (57kB)
> 
>      |████████████████████████████████| 61kB 1.9MB/s 
> 
> Collecting pathspec>=0.5.3 (from yamllint==1.20.0)
> 
>   Downloading https://files.pythonhosted.org/packages/5d/d0/887c58853bd4b6ffc7aa9cdba4fc57d7b979b45888a6bd47e4568e1cf868/pathspec-0.8.0-py2.py3-none-any.whl
> 
> Requirement already satisfied: pyyaml in /usr/lib/python2.7/dist-packages (from yamllint==1.20.0) (3.12)
> 
> Installing collected packages: pathspec, yamllint
> 
> ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pathspec-0.8.0.dist-info'
> 
> Consider using the `--user` option or check the permissions.
> 
> WARNING: You are using pip version 19.2.1, however version 20.0.2 is available.
> 
> You should consider upgrading via the 'pip install --upgrade pip' command.
> 
> The command "pip install yamllint==1.20.0" failed and exited with 1 during .
> ```

@bgurney-rh See my recommendation above (3)

**Comment by bgurney-rh** [comment]
Okay, I figured it was something to do with pip3.  Let's see how that goes.

**Comment by bgurney-rh** [comment]
Well, that didn't work:
```
pip3: command not found
```

**Comment by bgurney-rh** [comment]
I'm going to try the "addons:" variant to see if it will run when yamllint is installed via apt.

It's not what we were aiming for, but I want to see if I can get it working.

**Comment by bgurney-rh** [comment]
It looks like that worked.  For the sake of preservation, the diff for that commit is below:
```
diff --git a/.travis.yml b/.travis.yml
index b0572f7..7c5cb29 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,6 +10,7 @@ addons:
       - libcryptsetup-dev
       - keyutils
       - libkeyutils-dev
+      - yamllint

 language: rust
 jobs:
@@ -53,6 +54,9 @@ jobs:
       rust: stable
       env: TASK=release

+    - name: "run yamllint 1.20.0 on .travis.yml"
+      script: yamllint .travis.yml
+
 branches:
   only:
     - master
```

I was wondering if the only reason why "pip3" wasn't found was because TravisCI didn't receive a "python:" directive, so I'm going to try this:
```
diff --git a/.travis.yml b/.travis.yml
index b0572f7..dd5f2c7 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -53,6 +53,11 @@ jobs:
       rust: stable
       env: TASK=release

+    - name: "run yamllint 1.20.0 on .travis.yml"
+      python: "3.7.6"
+      install: pip3 install yamllint
+      script: yamllint .travis.yml
+
 branches:
   only:
     - master
```

**Comment by bgurney-rh** [comment]
...that didn't work; I see the same "pip3: command not found" error.

(One would think that, by installing Python 3, it would be motivated to have pip3 installed.  I guess not.)

I'm going to roll back to what works for now: the apt install method.

**Comment by mulkieran** [comment]
> ...that didn't work; I see the same "pip3: command not found" error.
> 
> (One would think that, by installing Python 3, it would be motivated to have pip3 installed. I guess not.)
> 
> I'm going to roll back to what works for now: the apt install method.

```pip-3``` is yet another possibility. This is a Rust project, and Travis knows that, which may be the source of the problem. Some default for Travis Python projects may not be happening here.

**Comment by jbaublitz** [comment]
> > ...that didn't work; I see the same "pip3: command not found" error.
> > (One would think that, by installing Python 3, it would be motivated to have pip3 installed. I guess not.)
> > I'm going to roll back to what works for now: the apt install method.
> 
> `pip-3` is yet another possibility. This is a Rust project, and Travis knows that, which may be the source of the problem. Some default for Travis Python projects may not be happening here.

The version of Ubuntu we're on might be using Python 2 by default. We may have to install Python 3 manually.

**Comment by mulkieran** [comment]
> > > ...that didn't work; I see the same "pip3: command not found" error.
> > > (One would think that, by installing Python 3, it would be motivated to have pip3 installed. I guess not.)
> > > I'm going to roll back to what works for now: the apt install method.
> > 
> > 
> > `pip-3` is yet another possibility. This is a Rust project, and Travis knows that, which may be the source of the problem. Some default for Travis Python projects may not be happening here.
> 
> The version of Ubuntu we're on might be using Python 2 by default. We may have to install Python 3 manually.

Yes. Looking in the manual I'ld say add the language specification back for that Travis task and keep trying with ```pip3```. The examples make it look like that should work.

**Comment by bgurney-rh** [comment]
I guess it would help if I had a "language: python" section in the file.  Let's try this:
```
--- a/.travis.yml
+++ b/.travis.yml
@@ -53,6 +53,14 @@ jobs:
       rust: stable
       env: TASK=release
 
+language: python
+jobs:
+  include:
+    - name: "run yamllint 1.20.0 on .travis.yml"
+      python: "3.7.6"
+      install: pip3 install yamllint==1.20.0
+      script: yamllint --strict .travis.yml
+
 branches:
   only:
     - master
```

**Comment by bgurney-rh** [comment]
What I indicated above fails syntax; trying this:
```
--- a/.travis.yml
+++ b/.travis.yml
@@ -53,6 +53,12 @@ jobs:
       rust: stable
       env: TASK=release
 
+    - name: "run yamllint 1.20.0 on .travis.yml"
+      language: python
+      python: "3.7.6"
+      install: pip3 install yamllint==1.20.0
+      script: yamllint --strict .travis.yml
+
 branches:
   only:
     - master
```

**Comment by mulkieran** [comment]
It's working! So all that's left is to add the target to the Makefile and make the Travis task use the Makefile target.

**Comment by bgurney-rh** [comment]
I added the Makefile target.  Here's what it looks like with a warning, if I remove the "---" at the beginning of the file:

```
yamllint --strict .travis.yml
.travis.yml
  1:1       warning  missing document start "---"  (document-start)

make: *** [Makefile:34: yamllint] Error 2
```

**Pull request closed without merging**
