### PR TITLE
Token API examples and changes to token API

### PR DESCRIPTION
**Pull request by jbaublitz**
This PR is meant to exercise the libcryptsetup-rs token API and make any necessary changes discovered while testing out the wrappers for this porting of the bindings.

### CODE REVIEW

**Comment by mulkieran** [comment]
@jbaublitz Please find out behavior on attempting to open an already opened device. Because of our reliance on udev we are certain at some point to miss a Stratis device in one step, and then encounter its luks2 device on the next step, and not be able to filter that luks2 device out from the ones to be opened. So we will have to be prepared for that situation.

Moved from #8.

**Comment by jbaublitz** [comment]
@bgurney-rh This failure is valid. I know how to fix this and will try to do it as soon as I can.

**Comment by jbaublitz** [comment]
> @jbaublitz Please find out behavior on attempting to open an already opened device. Because of our reliance on udev we are certain at some point to miss a Stratis device in one step, and then encounter its luks2 device on the next step, and not be able to filter that luks2 device out from the ones to be opened. So we will have to be prepared for that situation.
> 
> Moved from #8.

@mulkieran I added a new example for adding keys to the keyring to test this. Running `unlock-luks2-with-token` twice without deactivating the mapped device in between will result in:
```
Error: "IO error occurred: Device or resource busy (os error 16)"
```

**Comment by mulkieran** [comment]
It looks to me like GitHub is experiencing some kind of blip w/ this PR. It should be showing a conflict in the .travis.yml file since PR #14, but it isn't.

**Comment by jbaublitz** [comment]
Rebased.

**Comment by mulkieran** [comment]
There is a loopbacked test failure. I didn't look at it closely.

**Comment by jbaublitz** [comment]
@mulkieran This one is my fault. I think it would've been okay if I'd squashed the commits, but because I didn't, it reintroduced `/usr/sbin/mkfs.ext4` as opposed to `mkfs.ext4`. On Debian-based distros, `mkfs.ext4` is in `/sbin`.

**Pull request closed without merging**
