### PR TITLE
github actions: Upgrade Python to 3.8.6 and yamllint to 1.25

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: stratis-storage/project#231

### CODE REVIEW

**Review by mulkieran — APPROVED** [review]

**Comment by mulkieran** [comment]
We should probably fix the repo issue before merging this one...

**Comment by bgurney-rh** [comment]
The tests for #113 passed; I can re-create this PR rebased on top of that.

**Comment by mulkieran** [comment]
Ok!

**Comment by bgurney-rh** [comment]
I cherry-picked the commit to fix the repo; hopefully CI should pass now.

**Comment by mulkieran** [comment]
Looks good again.

**Review by jbaublitz — APPROVED** [review]

**Pull request merged**
