### PR TITLE
libcrypsetup-rs-sys 0.1.4

### PR DESCRIPTION
**Pull request by jbaublitz**
I'm going to merge this once CI passes in an effort to move along Fedora packaging.

### CODE REVIEW

**Comment by jbaublitz** [comment]
Rebased.

**Comment by mulkieran** [comment]
Moving this to July, to clear out the June board.

**Comment by jbaublitz** [comment]
Updated to fix the koji build.

**Comment by jbaublitz** [comment]
Koji build succeeded with these changes: [link here](https://koji.fedoraproject.org/koji/taskinfo?taskID=46530487).

Something seems to have changed on the Travis side as the version of libcryptsetup has dropped back below 2.2. I'll investigate later.

**Comment by jbaublitz** [comment]
It looks like Travis is no longer pulling from the `eoan` repository as you can see [here](https://travis-ci.org/github/stratis-storage/libcryptsetup-rs/jobs/704768614#L133).

**Comment by jbaublitz** [comment]
I changed from the Travis-supported repository syntax to manually adding and installing as needed for each step, and CI is now passing. This more closely mirrors what we do in Python anyway. @mulkieran Feel free to request that we change it back when you see this, but for now I'm going to merge and put out a new patch release.

**Pull request merged**
