### PR TITLE
Github actions prototype

### PR DESCRIPTION
**Pull request by jbaublitz**

### CODE REVIEW

**Comment by jbaublitz** [comment]
@mulkieran Ok this should be ready to review now!

**Review by mulkieran — CHANGES_REQUESTED** [review]
This looks good! Since we're getting no benefit from Travis anymore, might as well drop the .travis.yaml file entirely, and see what happens then. There is probably some configuration stuff to do in GitHub, also.

**Comment by jbaublitz** [comment]
Sounds good!

**Comment by jbaublitz** [comment]
@mulkieran We can uninstall Travis from our organization once we've migrated everything over. That appears to be the only step on the Github side. I found the button to press.

**Comment by mulkieran** [comment]
> @mulkieran We can uninstall Travis from our organization once we've migrated everything over. That appears to be the only step on the Github side. I found the button to press.

Great! We need to update the one self-referential task as well, i.e., linting our CI configuration file.

**Comment by jbaublitz** [comment]
Yeah I just saw that's hardcoded in the Makefile.

**Comment by jbaublitz** [comment]
@mulkieran Resolved!

**Review by mulkieran — CHANGES_REQUESTED** [review]
Looks ready! There's a branch protection rule that required Travis CI. I've dropped that requirement via the Settings tab, but didn't add the new tasks. I don't think the particular branch protection rules that require CI tasks are really all that useful; we might as well drop them and see if that works out just as well.

Feel free to put up a final PR whenever is convenient; we might as well merge these as they become ready.

**Pull request closed without merging**
