### PR TITLE
Add some Travis based CI

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
The appearance of Travis is changing, I'm trying to make sure it uses the legacy support, like all our other projects. This seems to have worked, but I need to find a way to de-authenticate the non-legacy support.

**Comment by jbaublitz** [comment]
The CI failures look like version-related issues. Some of those functions and fields in structs may have been added since the version that Travis installs. I'm going to put up an issue for adding a build script to verify a minimum version of the system libcryptsetup.

**Comment by mulkieran** [comment]
We expect the version on bionic to be 2.0.2, while the version on xenial was only 1.6.6. That might make all the difference.

**Comment by mulkieran** [comment]
Nope, we still have a failure. We need to install at least 2.2.0 of cryptsetup-dev to make this go, but then we should expect success.

**Comment by jbaublitz** [comment]
I will try to find the appropriate repo.

**Comment by mulkieran** [comment]
This is unlikely to succeed, probably we do need to find a custom repo, but if it does that would be really handy.

**Comment by mulkieran** [comment]
> This is unlikely to succeed, probably we do need to find a custom repo, but if it does that would be really handy.

It failed, so we do need that custom repo.

**Comment by jbaublitz** [comment]
Unstable has 2.2 in Ubuntu. I'm testing it in a VM now and I'll report back.

**Comment by mulkieran** [comment]
> Unstable has 2.2 in Ubuntu. I'm testing it in a VM now and I'll report back.

Great!

**Comment by jbaublitz** [comment]
I can confirm that installing cryptsetup from the `eoan` repository on Bionic both is successful from a build perspective and installs properly.

**Comment by jbaublitz** [comment]
Take a look at #6. CI is now successfully passing.

**Comment by mulkieran** [comment]
Great! I think the existing set of Travis task is good enough to go on. The ones I had originally put up were just all running "cargo build" due to some missing bits. @jbaublitz I've added you as co-committer and incorporated the repo spec. I think we should still use the bionic distribution; there is less risk of failing to install that way.

**Pull request merged**
